# Generated by Django 5.1.2 on 2024-10-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="pais",
            field=models.CharField(default="CL", max_length=2),
        ),
    ]
