# Generated by Django 5.1.2 on 2024-11-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_usuario_pais"),
    ]

    operations = [
        migrations.AddField(
            model_name="flan",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="flans/"),
        ),
    ]
