# Generated by Django 5.1.2 on 2024-11-25 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_flan_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flan",
            name="image",
        ),
    ]
