# Generated by Django 3.2 on 2024-06-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20240628_0213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contacto',
        ),
    ]
