# Generated by Django 3.2 on 2024-06-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_contactform_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('opinion', models.TextField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='web.flan')),
            ],
        ),
    ]
