# Generated by Django 3.2 on 2024-06-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_opinioncliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinioncliente',
            name='valoracion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
            preserve_default=False,
        ),
    ]
