# Generated by Django 3.2 on 2024-07-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20240702_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='created_at',
        ),
    ]
