# Generated by Django 5.1.2 on 2024-10-22 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compra", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carritoflan",
            name="orden_compra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="compra.ordencompra",
            ),
        ),
    ]
